# This file was generated by GoReleaser. DO NOT EDIT.
cask "gtmux" do
  version "1.0.17"

  on_macos do
    on_arm do
      sha256 "60036b155aaa71ef467509f3afe955375e43f36cd42302ab111e5acf8a4fe81e"
      url "https://github.com/chenchaoyi/gtmux/releases/download/v#{version}/gtmux-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "310d40c3997a827c8616e19251708b7ebe8a5af02516a1aa06ffad573cb56c5e"
      url "https://github.com/chenchaoyi/gtmux/releases/download/v#{version}/gtmux-#{version}-darwin-amd64.tar.gz"
    end
  end

  name "gtmux"
  desc "tmux/Ghostty session overview for macOS"
  homepage "https://github.com/chenchaoyi/gtmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtmux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gtmux"]
    end
  end

  # No zap stanza required
end
