# This file was generated by GoReleaser. DO NOT EDIT.
cask "gtmux" do
  version "0.12.44"

  on_macos do
    on_intel do
      sha256 "701e7f79b30c22c54112c869e04b8d39ef9e2f01ae5bfdb28442286b42b83ac5"
      url "https://github.com/chenchaoyi/gtmux/releases/download/v#{version}/gtmux-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "9dc8c8754a4df8152f39cb527fb8f9bb7d94459d16e3c37e44efe9d5cd1a2d51"
      url "https://github.com/chenchaoyi/gtmux/releases/download/v#{version}/gtmux-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "gtmux"
  desc "tmux/Ghostty session overview for macOS"
  homepage "https://github.com/chenchaoyi/gtmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtmux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gtmux"]
    end
  end

  # No zap stanza required

end
