# This file was generated by GoReleaser. DO NOT EDIT.
cask "gtmux" do
  version "0.44.15"

  on_macos do
    on_intel do
      sha256 "003fe746b695a6dbb3d145b465746934fbc27fa25abbda457e0ebf5a7a9c2bc4"
      url "https://github.com/chenchaoyi/gtmux/releases/download/v#{version}/gtmux-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "60cd629718add911c623e529bff21437ba990c5dc998ee00f1fbb3625d892f53"
      url "https://github.com/chenchaoyi/gtmux/releases/download/v#{version}/gtmux-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "gtmux"
  desc "tmux/Ghostty session overview for macOS"
  homepage "https://github.com/chenchaoyi/gtmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtmux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gtmux"]
    end
  end

  # No zap stanza required

end
