# This file was generated by GoReleaser. DO NOT EDIT.
cask "hammer" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "1cf4c5161261d3abf90b85d2a9aab46d04e3c59a68ecd48d621ff928d64c4b5c"
      url "https://github.com/chenchaoyi/hammer/releases/download/v#{version}/hammer-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "b26e27fc62b6008f9361961645d1cc765e4e4e1397928486f148fcd1d3bb2a04"
      url "https://github.com/chenchaoyi/hammer/releases/download/v#{version}/hammer-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c86b0ba4e63bb4fb4fc110b1a86b25b6db1207e996f054aa1ef1115074724b28"
      url "https://github.com/chenchaoyi/hammer/releases/download/v#{version}/hammer-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "22fd984b5cd9580da8deac64db900c671286159d7910c41466cbbb903e656e21"
      url "https://github.com/chenchaoyi/hammer/releases/download/v#{version}/hammer-linux-arm64.tar.gz"
    end
  end

  name "hammer"
  desc "Lightweight, agent-friendly HTTP(S) load generator"
  homepage "https://github.com/chenchaoyi/hammer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hammer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hammer"]
    end
  end
end
